### ISSUE TITLE
[Question] All rules in YAML file

### ISSUE THREAD

**Issue by lsaudon** [dart-code-checker/dart-code-metrics#1018]
**What do you want to discuss?**
Add a file in docs with all rules in YAML format like [Analysis Options](https://dart-lang.github.io/linter/lints/options/options.html).

**Comment by incendial** [comment]
@lsaudon actually, we have an idea to create presets. Will this work for you?

**Comment by lsaudon** [comment]
Like [lints](https://github.com/dart-lang/lints) with `core` and `recommended` ? I don't think so.

I would like to do as I did for the lints.
Have [all_lint_rules.yaml](https://raw.githubusercontent.com/lsaudon/calm_mind/main/all_lint_rules.yaml) with all the rules and in the file [analysis_options.yaml](https://raw.githubusercontent.com/lsaudon/calm_mind/main/analysis_options.yaml) disabled those I do not want.

**Comment by incendial** [comment]
> Like [lints](https://github.com/dart-lang/lints) with core and recommended ? I don't think so.

Yeah, but also there will be `all.yaml` with all the rules. 

And I think we can just add a link to that file in our docs and that'd enough.

**Comment by lsaudon** [comment]
I'm fine with it then. 😄

**Comment by incendial** [comment]
So here is the implementation https://github.com/dart-code-checker/dart-code-metrics/pull/1025
