### ISSUE TITLE
Participating in Hacktoberfest

### ISSUE THREAD

**Issue by lsaudon** [dart-code-checker/dart-code-metrics#1029]
It would be nice to participate to the hacktoberfest.

[Hacktoberfest Mainterners](https://hacktoberfest.com/participation/#maintainers)

**Comment by incendial** [comment]
@lsaudon could you elaborate?

**Comment by lsaudon** [comment]
Hacktoberfest is a month-long celebration of open-source projects, their maintainers, and the entire community of contributors.

This is to encourage contributions to open source projects.

**Comment by incendial** [comment]
You're suggesting to add DCM to this program?

**Comment by lsaudon** [comment]
Yes, that's right.
I think it's just adding a topic in about and putting labels in the issues and pull requests.
[The Dart language site](https://github.com/dart-lang/site-www) participates for example.

**Comment by incendial** [comment]
Done. I've added labels and topic, looks like that enough. Feel free to reopen if I did miss anything!
