### ISSUE TITLE
"all" presets don't contain all rules

### ISSUE THREAD

**Issue by NANASHI0X74** [dart-code-checker/dart-code-metrics#1079]
The rule presets under https://github.com/dart-code-checker/dart-code-metrics/tree/master/lib/presets
Don't contain all rules- at least avoid-cascade-after-if-null rule is missing.
I think they should be autogenerated like they are for the dart linter - https://raw.githubusercontent.com/dart-lang/linter/main/example/all.yaml

**Comment by incendial** [comment]
Thanks for noticing! As for autogeneration - there are no plans for adding it, but contributions are very welcome!

**Comment by incendial** [comment]
All rules now available in 5.1.0
