### ISSUE TITLE
[Feature request] Baseline support

### ISSUE THREAD

**Issue by ultraon** [dart-code-checker/dart-code-metrics#1091]
Does the package support a `baseline` feature?

What is the `baseline`?
 It is a file that contains many exclusions for existing issues. A baseline file is generated by the analysis tool for the existing project. And the feature is optional of course.

How can it help? 
 It makes it easier to include this tool in existing projects. After generating a baseline-file and running the analysis tool again it doesn't show any warnings, so, the engineers can be focused on new issues and work with existing ones in terms of maintenance work (aka work later).

**Comment by incendial** [comment]
@ultraon hi, in short, no, the package does not have this feature.

But if you could share an example (like another tool doing the same) and maybe a more broad description of a desired behaviour for this package, that would help a lot.

**Comment by ultraon** [comment]
Hello @incendial , yes of course, this is the tool for Kotlin projects: `Detekt`, see https://detekt.dev/docs/introduction/baseline/

**Comment by incendial** [comment]
Available in Teams 1.3.0, https://dcm.dev/docs/teams/cli/init/
