### ISSUE TITLE
`double-literal-format` quick-fix "everywhere in file"

### ISSUE THREAD

**Issue by FMorschel** [dart-code-checker/dart-code-metrics#1116]
Missing complement for "everywhere in file" with `lint double-literal-format`

"Add missing leading '0' __*everywhere in file*__ " 
"Remove redundant leading '0' __*everywhere in file*__ " 
"Remove redundant trailing '0' __*everywhere in file*__ "

**Comment by incendial** [comment]
Available in DCM for Teams version https://dcm.dev/for-teams
