### ISSUE TITLE
Support latest analyzer 5.10.0

### ISSUE THREAD

**Issue by asaarnak** [dart-code-checker/dart-code-metrics#1216]
![image](https://user-images.githubusercontent.com/808420/229577185-45eaebb0-cd7a-477f-a310-c88bd7e431e5.png)

**Comment by asaarnak** [comment]
Seems like there is a pull request already: #1214

**Comment by asaarnak** [comment]
Maybe we should use `^5.1.0` in this dependency as it shouldn't be breaking change?

**Comment by incendial** [comment]
> Maybe we should use ^5.1.0 instead of ">=5.1.0 <5.9.0" in this dependency as it shouldn't be breaking change?

It's not possible due to the analyzer not following the semver. Sometimes breaking changes can appear in minor releases.

**Comment by incendial** [comment]
Available in 5.7.1

**Comment by asaarnak** [comment]
> > Maybe we should use ^5.1.0 instead of ">=5.1.0 <5.9.0" in this dependency as it shouldn't be breaking change?
> 
> It's not possible due to the analyzer not following the semver. Sometimes breaking changes can appear in minor releases.

Ok, thanks! How often this happens?

**Comment by incendial** [comment]
Have no idea, but what matters is that it happens
