### ISSUE TITLE
[BUG] (VsCode) No quick actions to ignore rules

### ISSUE THREAD

**Issue by petrnymsa** [dart-code-checker/dart-code-metrics#1235]
### Environment and configuration

DCM version: 1.3.0
Dart SDK version:  Dart SDK version: 2.19.6

<details>
<summary>Configuration</summary>

```yaml
OS: Windows 11, Version 10.0.22621 Build 22621
VSCode: 1.78.2
DCM extension: 1.3.0
```
</details>

### What did you do?

Standard "lints" can be via "quick-action" ignored (in line or in whole file), e.g. 

![image](https://github.com/dart-code-checker/dart-code-metrics/assets/21087414/1454704f-0e24-4dcf-9bfc-4ddd99452c73)

But for "DCM" based rule / lint there is no quick action, for example 

![image](https://github.com/dart-code-checker/dart-code-metrics/assets/21087414/a4ab09e5-bb69-4c60-ab5b-061f1041f57a)

**Rule**:   avoid-throw-in-catch-block

### What did you expect to happen?

For DCM rules there will be quick-action for ignore

### What actually happened?

No quick-action available

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by incendial** [comment]
This works as intended. Consider switching to the Teams version where this is solved.
