### ISSUE TITLE
[Idea] formalise rule naming

### ISSUE THREAD

**Issue by dkrutskikh** [dart-code-checker/dart-code-metrics#146]
That's an example! https://github.com/dart-lang/linter/blob/master/doc/WritingLints.MD
https://github.com/dart-lang/sdk/blob/5bac4d9b0cdc12a21d0b9914a3c8c0d9716aa705/pkg/front_end/lib/src/fasta/diagnostics.md#guide-for-writing-diagnostics

**Comment by incendial** [comment]
Other naming examples:
* https://eslint.org/docs/rules/
* https://palantir.github.io/tslint/rules/
* https://dart-lang.github.io/linter/lints/

**Comment by incendial** [comment]
Python: https://www.flake8rules.com/

**Comment by incendial** [comment]
Closing due to https://github.com/dart-code-checker/dart-code-metrics/issues/520
