### ISSUE TITLE
[Rule change] Add rules for static field/method in member ordering rule

### ISSUE THREAD

**Issue by Mahakon** [dart-code-checker/dart-code-metrics#155]
Add rules for static field/method in member-ordering rule

**What rule do you want to change?**
member-ordering

**How will the change be implemented? (New option, new default behavior, etc.)?**
new option, just we will be able to make order for static methods/fields too

**Please provide some example code that this change will affect:**

```dart
class RescheduleUpdateComponent {
  @HostBinding('class')
  static const String hostClass = 'reschedule-update';

  final DateTimeFormatter _dateTimeFormatter;
 
  @HostBinding(‘class.active’)
  bool get isActive() => _viewState.isActive;
}
```

**What does the rule currently do for this code?**
- member-ordering:
        order:
          - static_fields
          - private_fields
          - public_fields
          - angular_host_bindings
in such configuration we can change order for static methods

**What will the rule do after it's changed?**
can make particular order for static field/method

**Are you willing to submit a pull request to implement this change?**
I

**Comment by incendial** [comment]
Will be closed by #245 with a separate rule for now.
