### ISSUE TITLE
[Question] How to use It with Gitlab CI + Codeclimate

### ISSUE THREAD

**Issue by btd1337** [dart-code-checker/dart-code-metrics#206]
Hi @srvc-wrikegithub, 

Firstly, congratulations on this great job.

I have one question to you:

How use this with `Flutter` + `Gitlab CI` + `Codeclimate`?

I follow [this tutorial](https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html) but It's won't works for me.

**Comment by fredgrott** [comment]
I found the answer for you! You need to follow the codeclimate-dart directions from wrike at here:
https://github.com/wrike/codeclimate-dart

as it wraps dart code metrics so that codeclimate can understand it and process the results

**Comment by dkrutskikh** [comment]
@btd1337 Sorry for delay, we finished updating the [documentation](https://dartcodemetrics.dev/docs/cli/analyze#gitlab) about work with GitLab.

**Comment by incendial** [comment]
Closing this for now. Feel free to reopen it if the the documentation we have doesn't answer your question.
