### ISSUE TITLE
[Question] Would it be possible to change dependency for args?

### ISSUE THREAD

**Issue by ovestoerholt** [dart-code-checker/dart-code-metrics#208]
**What do you want to discuss?**
If you could change dependency for args package from 1.44 to 2.0.0-nullsafety this library could be used with Flutter 1.25 and beyound with null safety suppor.
Possible?

**Comment by incendial** [comment]
@ovestoerholt hi, sorry for the long response, it seems that changing `args` package version will require dart 2.12 and migrating dart-code-metrics to null safety too. But currently we blocked by analyzer_plugin package, that is used to connect to analysis server.

**Comment by incendial** [comment]
@ovestoerholt hi, we finally release a stable null safety version where this problem was resolve. Please take a look if you still interested!

**Comment by ovestoerholt** [comment]
Perfect! Super thanks! 😊
