### ISSUE TITLE
can we get a directory parameter?

### ISSUE THREAD

**Issue by fredgrott** [dart-code-checker/dart-code-metrics#211]
what would be nice is a way to set our own directory for where the reports get written to

I enjoy using this plugin. keep up the good work.

**Comment by incendial** [comment]
@fredgrott hi, sorry for the long response, what report type are you talking about, html?

**Comment by fredgrott** [comment]
Yes html, please thanks

**Comment by dkrutskikh** [comment]
@fredgrott we publish new version, can you try it out?
