### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by incendial** [dart-code-checker/dart-code-metrics#216]
Release v3.0.0 checklist
- [x] migrate analyzer_plugin package (or wait until[ it will be migrated](https://github.com/dart-lang/sdk/issues/45236))
- [x] migrate the package
- [x] publish the package
- [x] rework json reporter (completely new report format) 
- [x] merge code_checker
- [ ] ~~drop support for angular rules (?)~~
- [x] rework public api
  - [x] unify `exclude` and `ignore-files` arguments (`exclude` is now used everywhere)
  - [x] rename `maximum-nesting` to `maximum-nesting-level`
  - [x] rename `number-of-arguments` to `number-of-parameters`
  - [x] rename all rules config from snake_case to kebab-case with backward compatibility
- [x] remove rules:
  - [x] `potential-null-dereference` (useless after null safety introduction)
  - [x] `prefer-trailing-comma-for-collection` (`prefer-trailing-comma` fully covers its cases)
- [x] add new rules:
  - [x] `member-ordering-extended`

**Comment by dkrutskikh** [comment]
@fredgrott I think yes. Our goal support latest Flutter and Dart versions.

**Comment by GroovinChip** [comment]
Hi everyone, is there any movement on this?

**Comment by GroovinChip** [comment]
FYI, the `source_span`  dependency conflicts with the version in `flutter_test`:

```
Because every version of dart_code_metrics from git depends on source_span ^1.8.1 and every version of flutter_test from sdk depends on source_span 1.8.0, dart_code_metrics from git is incompatible with flutter_test from sdk.
```

This is when I target `dart_code_metrics` from git like so:
```
  dart_code_metrics:
    git: git@github.com:dart-code-checker/dart-code-metrics.git
```

**Comment by incendial** [comment]
@GroovinChip thanks! That was an unexpected version pin, to be honest. I have downgraded the version constraints.

**Comment by GroovinChip** [comment]
> @GroovinChip thanks! That was an unexpected version pin, to be honest. I have downgraded the version constraints.

Sure thing! I'll try it out soon let you know how it goes.

**Comment by GroovinChip** [comment]
Okay, `flutter pub get` works now. Thank you!

**Comment by incendial** [comment]
Prerelease version is now available on Pub, here is [the link](https://pub.dev/packages/dart_code_metrics/versions/3.0.0-nullsafety.1).

**Comment by GroovinChip** [comment]
https://twitter.com/GroovinChip/status/1379440194710036482?s=19

😁

**Comment by psrcek** [comment]
I get the following trying to use the prerelease version:

```
$ flutter pub get
Running "flutter pub get" in aio...                             
Because every version of flutter_driver from sdk depends on file 6.0.0 and dart_code_metrics >=3.0.0-nullsafety.0 depends on file ^6.1.0, flutter_driver from sdk is incompatible with dart_code_metrics >=3.0.0-nullsafety.0.

So, because [app] depends on both dart_code_metrics ^3.0.0-nullsafety.1 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because [app] depends on both dart_code_metrics ^3.0.0-nullsafety.1 and flutter_driver any from sdk, version solving failed.)
exit code 1
```

I have flutter_driver included like this in my pubspec:
```
dev_dependencies:
  flutter_driver:
    sdk: flutter
```


I'm using flutter version `2.0.4`

**Comment by dkrutskikh** [comment]
@psrcek thank you for feedback. I'll release new version with fix of your problem in a couple of hours.

**Comment by psrcek** [comment]
I don't see the new version on pub.dev yet :smile: Maybe you forgot to release it? `3.0.0-nullsafety.1` still includes the issue.

**Comment by incendial** [comment]
@psrcek sorry for the delay, but we found a critical issue with the plugin bootstrapping, so, if you want to use it as a plugin to the analyzer and see issues in IDE - it will not work yet, details can be found [here](https://github.com/dart-code-checker/dart-code-metrics/issues/253#issuecomment-815510423).

**Comment by dkrutskikh** [comment]
@psrcek we publish 3.0.0-nullsafety.2 version

**Comment by incendial** [comment]
Stable null safety release is now available [on pub](https://pub.dev/packages/dart_code_metrics)! 🎉
