### ISSUE TITLE
update to crypto 3.0 to match integration-test driver?

### ISSUE THREAD

**Issue by fredgrott** [dart-code-checker/dart-code-metrics#237]
cannot use as you are still on crypto 2.0.x when test driver is crypto 3.0.x here is my pub output:

Because dart_code_metrics >=1.6.0 depends on crypto ^2.0.6 and every version of flutter_driver from sdk depends on crypto 3.0.0, dart_code_metrics >=1.6.0 is incompatible with flutter_driver from sdk.

And because integration_test 1.0.2+2 depends on flutter_driver any from sdk and no versions of integration_test match >1.0.2+2 <2.0.0, dart_code_metrics >=1.6.0 is incompatible with integration_test ^1.0.2+2.
So, because log_error depends on both integration_test ^1.0.2+2 and dart_code_metrics ^2.4.1, version solving failed.

pub get failed (1; So, because log_error depends on both integration_test ^1.0.2+2 and dart_code_metrics ^2.4.1, version solving failed.)
exit code 1

**Comment by incendial** [comment]
@fredgrott hi, we finally released a stable null safety version where this problem was resolved. Please take a look if you still interested!
