### ISSUE TITLE
[Question] What is the proper usage of the GitHub reporter?

### ISSUE THREAD

**Issue by GroovinChip** [dart-code-checker/dart-code-metrics#246]
[This page](https://github.com/dart-code-checker/dart-code-metrics/blob/master/doc/reporters/github-reporter.md) doesn't make it very clear how one might use the GitHub reporter in an Action. What is the proper usage?

**Comment by incendial** [comment]
@dkrutskikh could you please help with that?

@GroovinChip AFAIK, we have it enabled and that is all config that I see right now https://github.com/dart-code-checker/dart-code-metrics/blob/master/.github/workflows/build.yaml#L33.

**Comment by dkrutskikh** [comment]
@GroovinChip after finish work on null-safety stable release. We start works on Github action. At this time it's simple report whose report only about issues.

**Comment by GroovinChip** [comment]
That's fine, I'm just unsure of how to use it at all. When I select it as the reporter using the CLI, the output doesn't seem to be recorded anywhere but the console. And the docs weren't clear either.

Looking forward to actions improvements after null safety is released :) thanks!

**Comment by GroovinChip** [comment]
@dkrutskikh Since null safety has been released to stable, do you have any thoughts on when code metrics for actions will see some progress?

**Comment by furaiev** [comment]
Hello, @dkrutskikh @incendial ,
Thank you for this tool!

I have an issue with git report.
When I run
```
- name: Run Code Metrics
   run: dart run bin/metrics.dart --reporter=github lib
```
I get an error that bin/metrics.dart isn't found.

**Comment by incendial** [comment]
@GroovinChip we merged the PR with the updated docs, please check it out.

Great thanks to @furaiev for creating the PR! 🎉
