### ISSUE TITLE
[BUG] Web link to rule details provided by IDE does not work

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#267]
* **Dart code metrics version:** 3.0.0
* **Dart sdk version:** 2.13.0-219.0.dev (dev) (Thu Apr 8 11:44:31 2021 -0700) on "windows_x64"

I am using Visual Studio with `dart-code-metrics`. When I click to a rule link provided by the plugin in tooltip (or problems panel)

![image](https://user-images.githubusercontent.com/18419515/114839434-6e136f00-9dde-11eb-8f5f-7ca6514a8411.png)

I am getting 404 error at `https://dart-code-checker.github.io/dart-code-metrics/rules/newline-before-return.html`.

Should this be fixed?

**Comment by dkrutskikh** [comment]
@roman-petrov thank you for feedback. This issues will be fix in nearest version

**Comment by roman-petrov** [comment]
@dkrutskikh thank you for great support!
