### ISSUE TITLE
[Question] Are there still long term development & support plans?

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#271]
At our company we plan to start using `dart-code-metrics` in our Flutter design system and this would be a big and a long term project. 

Recently I got a [news](https://habr.com/ru/company/wrike/blog/551964/) that says Wrike company long term plan is to move away from Dart language.

I know that currently the project is actively being improved - thank you for great work! But now I a bit wonder if you still have long term intentions to be maintainers of this project and continue its development & support?

**Comment by incendial** [comment]
Hi @roman-petrov, first of all, I’m very happy to know that your company is planning to use `dart-code-metrics` for a long-term project. It’s very exciting!

I’ll try to explain everything about our development and support plans, if you will still have any questions, feel free to ask.

As you might have noticed, we moved the project to a different Github org. some time ago and it should not be associated with Wrike anymore. At Wrike we were mainly developing it in our free time and had lack of support from the company with the project development.

After moving it out we increased the effort we put into the project and we think that it’s a good way to give back to the community and we’re very excited and happy that our work is helping other people be more productive and produce a better code.

We have a lot of features to add to the project and we will do that, but please remember that it’s an open source and we can’t spent all our time doing it. 
We plan to support it for a long time and I hope we will increase the amount of maintainers in the future.

**Comment by roman-petrov** [comment]
@incendial thank you for great explanation! that's all I would like to hear :)

Now I understand that this product not associated with Wrike anymore and it's also clear that success of this project might heavily depend on contribution activity. So I will try to do my best to promote it inside our company and hope we will provide some contributions in future.

I have some ideas about rules enforcing (pure) functional + immutable design approach, I will almost _have to_ enforce this in my team so I will almost _have to_ contribute:)

Also, I hope the project will became part of [Flutter Favorite Program](https://flutter.dev/docs/development/packages-and-plugins/favorites) so it will be easily discoverable on `pub.dev`. Maybe it's time to think, what should be done here...

Thanks again!

**Comment by dkrutskikh** [comment]
@roman-petrov can you create issues for your ideas?

**Comment by roman-petrov** [comment]
@dkrutskikh sure, I will. At the moment I don't have exact proposal, just some rough ideas. I will create feature request issues when I will have better understanding what do I like to enforce. I also plan to make code contribution myself if we decide to implement these rules after discussion.

**Comment by incendial** [comment]
> I will create feature request issues when I will have better understanding what do I like to enforce. I also plan to make code contribution myself if we decide to implement these rules after discussion.

That sounds great, if you'll have any questions about the code I will be happy to help.

> Also, I hope the project will became part of Flutter Favorite Program so it will be easily discoverable on pub.dev. Maybe it's time to think, what should be done here...

We discussed it and seems that we need to become a verified publisher which requires a website (as I understand). Hope, we will resolve this in the nearest future.

> So I will try to do my best to promote it inside our company and hope we will provide some contributions in future.

Thank you very much for your effort.

**Comment by roman-petrov** [comment]
great, hope to see `dart_code_metrics` on top of `pub.dev` with `Flutter Favorite` badge this year!
