### ISSUE TITLE
[Question] --reporter=github lib

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#274]
Hello, thank you for your tool.

I have a question regarding to `--reporter=github`:

When I run `flutter pub run dart_code_metrics:metrics --reporter=github lib` in my project I get only 2 `Long method.` warnings.
But when I run `flutter pub run dart_code_metrics:metrics lib`, I get a pretty long list of warnings and alarms.

Is it a CLI bug, or I missed something?

**Comment by dkrutskikh** [comment]
@furaiev currently GitHub reporter support only anti-patterns and code analysis rules

**Comment by furaiev** [comment]
@dkrutskikh I see, thank you.
Are `metrics` in the plans?

**Comment by QuirijnGB** [comment]
Is there a reason that it hasn't been done? Happy to have a stab at it. 
Im asking because I noticed the `github_reporter` resides in the `obsolete` directory. Dont want to waste my time on it if itll get dropped

**Comment by dkrutskikh** [comment]
@QuirijnGB current implementation is really obsolete. Currently we work on GitHub action, and I hope we release them soon.

**Comment by QuirijnGB** [comment]
@dkrutskikh 👍  Sounds good. Let me know if i can help

**Comment by dkrutskikh** [comment]
@QuirijnGB @furaiev sorry for long response. Now you can try to use our [GitHub Action](https://github.com/dart-code-checker/dart-code-metrics-action).

**Comment by incendial** [comment]
Closing this for now. Feel free to reopen it if the the documentation we have doesn't answer your question.
