### ISSUE TITLE
[Rule change] long-method exclude build Widget methods

### ISSUE THREAD

**Issue by unger1984** [dart-code-checker/dart-code-metrics#297]
**What rule do you want to change?**

long-method

Flutter build methods that return a Widget must be excluded from the antipattern. They can be really big and this is not an anti-pattern. For their validation, the cyclomatic-complexity metric is enough.

With #296 Issue, cyclomatic-complexity and avoid-returning-widgets this will allow more flexible customization of code verification for flutter

**Comment by dkrutskikh** [comment]
landed in 4.0.0
