### ISSUE TITLE
[BUG] Many tests are failing when running on Windows

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#301]
To reproduce this issue just clone the repository on Windows machine and run `flutter_test`: [flutter_test_output.txt](https://github.com/dart-code-checker/dart-code-metrics/files/6406366/flutter_test_output.txt). 

This is happening due to differences in path separators. This should be easy to fix issue, but I wonder if we should have some common patterns in code for this.

**Comment by incendial** [comment]
I don't think that the `flutter_test` command should be used for this repo. It's `dart test` instead. Or I didn't get the point 🙂

> but I wonder if we should have some common patterns in code for this.

We definitely should. Seems like we need to create a helper function for the path building.

**Comment by roman-petrov** [comment]
> I don't think that the `flutter_test` should be used for this repo. It's `dart test` instead. Or I didn't get the point 🙂

Sure, it's my mistake - I work on Flutter projects so I'am tied to Flutter workflow:)

> We definitely should. Seems like we need to create a helper function for the path building.

So, maybe, we should to have some convention for this when we construct path. If we construct all paths in code using `path` library methods the problem should be gone.

But I also a bit wonder if we can have a lint for this instead of having just a code convention. This lint might help people (and us) to improve cross-platform project compatibility.

For example, we can detect strings like

`'/usr/home/dir'`
`'data/dir1/dir2'`
`'data\projects/myproject'`
`'Program Files\\Program'`

and suggest to uses `path` library to construct paths.

Most of the time the purpose of such strings is to be paths or URL parts. Although there is no 100% correct way to detect path strings in code I suppose we still will not get too many false positives for this lint. 

What do you think about such lint?

**Comment by incendial** [comment]
Sorry, kinda forgot to answer this.

> But I also a bit wonder if we can have a lint for this instead of having just a code convention

I don't think we need an internal lint to check this, can just convert file path at runtime.

Also, is this issue still reproducing, because I remember that @dkrutskikh fixed something similar?

**Comment by roman-petrov** [comment]
@incendial, sorry, I forget to answer too :)

The situation is much better now: I see only two failing tests on Windows: `lint_analyzer_test` and `exclude_utils_test`.

I think we should stop manually checking if Windows tests are not failing. We can set up a GitHub action to run Windows tests only without building/linting. I currently don't have any experience in GitHub actions, but I can try to make a PR.

So, as I think, we should :
1. Add a GitHub action `Run tests on latest Windows` that will run on `windows-latest`
2. Fix remaining issues in tests on Windows

What do you think about this approach?

**Comment by incendial** [comment]
@roman-petrov do we really need to run tests on Windows? Seems like the infrastructure won't change and it's unnecessary.

>  I see only two failing tests on Windows: lint_analyzer_test and exclude_utils_test.

And it's still a problem with the path?

**Comment by roman-petrov** [comment]
I didn't take deep research on the remaining problems so I am not sure about that.

Actually, I still think we have to implement some regression control for Windows tests (additional GitHub action or something else). 

Right now even if we fix the remaining issues with tests on Windows, someone can easily introduce a regression in a PR, and tests on Windows might become broken again...
