### ISSUE TITLE
[New feature: blocked] Run `dart_code_metrics` when running `dart analyze` command

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#313]
Actually, this is not just a question and closer to feature request. But there is almost nothing should be done in `dart_code_metrics` to implement this feature. 

A relatively new `dart analyze`  command (which replaces `dartanalyzer`) uses analysis server to perform linting. `dart` tool [launches analysis server](https://github.com/dart-lang/sdk/blob/master/pkg/dartdev/lib/src/commands/analyze.dart#L115) and communicates with it to get code analysis issues. I actually spent some time and investigated this scenario. I see that plugins (and `dart_code_metrics` plugin) in such scenario are being loaded and work properly.

But issues found by `dart_code_metrics` are not reported in this scenario: analysis server shutted down too early by `dart` tool. 

There is an issue in Dart SDK repository which blocks us from using the plugin inside `dart analyze` workflow:
[`dart analyze` does not know when analyzer plugin results are complete](https://github.com/dart-lang/sdk/issues/38407)

I decided to open this issue just to track Dart SDK issue .  The issue has `P3` status and I hope it will be fixed relatively soon. My proposal is document ability to run `dart_code_metrics` using `dart analyze` after Dart SDK issue is fixed.  

I suppose it would be more convenient to use the plugin with  "standard" workflow with `dart analyze` , please let me know what do you think about this.

**Comment by incendial** [comment]
Yeah, we faced situations when running `dart analyze` could eventually fail because of a plugin issue report ([like this one](https://github.com/dart-code-checker/dart-code-metrics/runs/2311793200?check_suite_focus=true#step:5:6)), but unfortunately had no time to investigate it further or even help fix it.

I think it'd be great to have this feature.

**Comment by incendial** [comment]
But we have other ideas for Cli commands, so we will not be able to remove it completely.

**Comment by roman-petrov** [comment]
> But we have other ideas for Cli commands, so we will not be able to remove it completely.

Actually, I am proposing just to have new feature and document it when Dart SDK issue is fixed. I understand that CLI integration can give us more than just analyzer plugin so I am not proposing to remove CLI commands.

Let's have this issue open if you don't mind: I will try to track it myself and hopefully will provide documentation PR when DartSDK issue is resolved.

**Comment by incendial** [comment]
Considering the overall direction with the DCM as a separate executable, this feature request is now obsolete.
