### ISSUE TITLE
[Question] What is maintability index metric?

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#333]
When trying to run `dart-code-metrics` in our large enough project I see that it fails **silently** on some packages with non zero exit code  but nothing reported to console.

When I launch with  `--reporter=html`  I see `maintainabilityIndex` violation but as I see this is undocumented feature and it is impossible to configure maintability index levels in analysis options.

In project source code I see that maintability index metrics [has no documentation](https://github.com/dart-code-checker/dart-code-metrics/blob/master/lib/src/analyzers/lint_analyzer/lint_analyzer.dart#L396) and levels are [hard-coded](https://github.com/dart-code-checker/dart-code-metrics/blob/master/lib/src/analyzers/lint_analyzer/lint_analyzer.dart#L420). 

I'm not quite sure if I understood all of this correctly, but currently I don't see any way to avoid this `maintabilityIndex` violation in our code base.

So I would like to discuss what can be done here and maybe we should finally create a feature request / bug report.

**Comment by dkrutskikh** [comment]
@roman-petrov this is our first implementation of https://docs.microsoft.com/en-us/visualstudio/code-quality/code-metrics-maintainability-index-range-and-meaning?view=vs-2019

**Comment by roman-petrov** [comment]
@dkrutskikh thank you, now I understand the source of this metric, but it is currently undocumented and I do not see any possibility to disable or configure it. Should we improve this somehow?

**Comment by roman-petrov** [comment]
Сlosing since it's answered / solved recently in https://github.com/dart-code-checker/dart-code-metrics/pull/452
