### ISSUE TITLE
Can plugin read `analysis_options.yaml` config?

### ISSUE THREAD

**Issue by fartem** [dart-code-checker/dart-code-metrics#335]
I'm have configured `analysis_options.yaml` with specific rules for this plugin. In IDE all works fine, but on CI when I'm running plugin check from shell, config cannot applying. It is normal behaviour? Can I exclude rules in plugin from CLI run?

**Comment by dkrutskikh** [comment]
@fartem sure, we support configuration via analysis_options.yaml in both modes (cli / plugin). Can you provide more details about your project and configurations?

**Comment by fartem** [comment]
@dkrutskikh Yes.

`analysis_options.yaml` config:

```yaml
dart_code_metrics:
  rules:
    - avoid-returning-widgets
```

On CI plugins runs with:

```shell
$ flutter pub global activate dart_code_metrics
$ flutter pub global run dart_code_metrics:metrics lib
```

**Comment by dkrutskikh** [comment]
@fartem can you contact with me for more details?

**Comment by fartem** [comment]
@dkrutskikh Sure.

**Comment by fartem** [comment]
In my case, plugin send errors not about rules.
