### ISSUE TITLE
[New feature] Technical debt cost

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#371]
Today from flutter PR https://github.com/flutter/flutter/pull/83846 I found an interesting module in Flutter Device Lab, [technical debt cost calculation](https://github.com/flutter/flutter/blob/master/dev/devicelab/bin/tasks/technical_debt__cost.dart). 

If flutter performs such a task it might be a good idea to have something similar in `dart_code_metrics`. This is just an idea, please feel free to close it or move it into some backlog if you like.

**Comment by incendial** [comment]
That looks so cool! Thanks for sharing that idea and I think we should implement it too with customizable costs. In 4.0 we will support commands and that looks like a great candidate for a new command.

**Comment by roman-petrov** [comment]
that's great you like it!

**Comment by roman-petrov** [comment]
@incendial - am going to ten day vacation today. So not now - maybe I will decide later. We will definitely need such feature in our company, but this will happen in a few month.

**Comment by incendial** [comment]
> am going to ten day vacation today. So not now - maybe I will decide later. We will definitely need such feature in our company, but this will happen in a few month.

Okay, have a nice vacation!

**Comment by luca-venir** [comment]
This is... actually awesome! Is this feature going anywhere soon? I wish I could help by implementing it myself, unluckily I'm not skilled enough, yet.

**Comment by incendial** [comment]
We currently have different options on how to implement dept cost calculation and no final vision yet. So, I don't think that we'll add it very soon, but more likely in several months.

**Comment by dkrutskikh** [comment]
Sub steps:
https://github.com/dart-code-checker/dart-code-metrics/pull/502

**Comment by dkrutskikh** [comment]
Available in 4.8.0 release 🚀
