### ISSUE TITLE
[BUG] Quick fix action performs on wrong position using part file

### ISSUE THREAD

**Issue by malikwang** [dart-code-checker/dart-code-metrics#378]
* **Dart code metrics version:**  3.3.5
* **Dart sdk version:** 2.12.3

 [Video](https://github.com/malikwang/quick_fix/blob/main/result.mov)

 [Source code](https://github.com/malikwang/quick_fix)

**Comment by incendial** [comment]
@malikwang thank you for reporting this, the fix is on the way #379

**Comment by dkrutskikh** [comment]
@malikwang fixed in version 3.3.6

**Comment by malikwang** [comment]
> @malikwang fixed in version 3.3.6

Thanks for reply.
I also implement my custom analyze rule using quick fix.
So i would like to more more details about how to fix this issue.
Howerver, [the comment](https://github.com/dart-code-checker/dart-code-metrics/pull/379/commits/d2d152db8f62cf20f20fd29ad032cce3991b006a) seems unrelated to this issue.
