### ISSUE TITLE
[BUG] always-remove-listener edge case (generic)

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#387]
There is an edge case when `always-remove-listener` doesn't recognize a removed listener: the generic listenable that passed to the class.

* **Minimal reproducible code:** https://github.com/furaiev/always-remove-listener/blob/main/lib/main.dart
* **Dart code metrics version:** ^4.0.0
* **Dart sdk version:** 2.12.2 (stable)

**Comment by incendial** [comment]
@furaiev big thanks for the example, seems like a problem with a controller being a field of a stateful widget and not of a state.

**Comment by furaiev** [comment]
@incendial it's more tricky. If you replace ValueNotifier with e.g. ScrollController, and remove all generics <T>, the rule works as expected.
So, it seems like an issue only with Generic Listenable that being a field of a stateful widget and not of a state.

**Comment by incendial** [comment]
Hmm... good to know, thanks. I've marked it as 4.1, but I hope we'll fix and release it sooner.

**Comment by incendial** [comment]
Thanks again for the example, it seems that somehow `ValueNotifier<T>` resolves to `ValueNotifier<dynamic>` and `ValueNotifier<dynamic>` is not equal to `ValueNotifier<dynamic>` 😄

**Comment by incendial** [comment]
@furaiev fixed in 4.0.1.
