### ISSUE TITLE
[Rule change] avoid-unused-parameters conflict with avoid_renaming_method_parameters

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#388]
**What rule do you want to change?** 
`avoid-unused-parameters`

Projects created with flutter create using Flutter version 2.3.0-12.0.pre or newer are already enabled to use the latest set of recommended lints. One of the recommended lints is `avoid_renaming_method_parameters` that has a conflict with `avoid-unused-parameters`.
https://flutter.dev/docs/release/breaking-changes/flutter-lints-package#summary

**How will the change be implemented? (New option, new default behavior, etc.)?**
Exclude the overridden methods from the rule.

**Please provide some example code that this change will affect:**

```dart
class SomeOtherClass extends StatelessWidget {
  @override
  Widget build(BuildContext _) {} // LINT avoid_renaming_method_parameters
}

class SomeOtherClass extends StatelessWidget {
  @override
  Widget build(BuildContext context) {} // LINT avoid-unused-parameters
}
```

**Comment by dkrutskikh** [comment]
@furaiev thanks for feedback, please provide version of Dart Code Metrics

**Comment by furaiev** [comment]
^4.0.0

**Comment by furaiev** [comment]
Oh, it seems like this rule already excludes overridden methods as of the 4th version, correct?

**Comment by incendial** [comment]
> Oh, it seems like this rule already excludes overridden methods as of the 4th version, correct?

Yeah, we decided to remove this check exactly because of this conflict.
