### ISSUE TITLE
[BUG] can't ignore cyclomatic complexity

### ISSUE THREAD

**Issue by grafovdenis** [dart-code-checker/dart-code-metrics#389]
* **Dart code metrics version:** 4.0.0
* **Dart sdk version:** 2.13.3

**Please show your full configuration:**

I use default config for metrics, so `cyclomatic-complexity` is set to 20.

<details>

<summary>Configuration</summary>

```yaml
analyzer:
  plugins:
    - dart_code_metrics
```

</details>

**What did you do?**

I wrote complex function, which complexity is 21.

**What did you expect to happen?**

I'd like to ignore `cyclomatic-complexity` for this function.

**What actually happened?**

When i use `// ignore: code-metrics` or `// ignore: cyclomatic-complexity`, nothing happends.

**Comment by imtoori** [comment]
same here 
actually I'm trying to disable cyclomatic complexity for the whole project and it's not working

**Comment by incendial** [comment]
@imtoori oh, looks like we accidentally removed it, sorry. Are you trying to disable it for plugin or cli? Or both?

**Comment by incendial** [comment]
@grafovdenis @imtoori fixed in 4.0.1.
