### ISSUE TITLE
[Dart Analyzer getting crashed on VS Code if Install this dependecies] 

### ISSUE THREAD

**Issue by Parvinderjit** [dart-code-checker/dart-code-metrics#399]
* **4.0.1**
* **2.13.4**

**Please show your full configuration:**

<details>
include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
  - dart_code_metrics
  errors:
    unnecessary_overrides: warning
    avoid_function_literals_in_foreach_calls: ignore
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 100
    maximum-nesting-level: 5
    weight-of-class: 0
    number-of-parameters: 10
    number-of-methods: 15
  metrics-exclude:
    - test/**
    - lib/*.g.dart
    - lib/models/**
    - lib/common_widgets/**
    - lib/gen/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
    - annotate_overrides
    - unnecessary_overrides
    - avoid_empty_else
    - empty_catches

</details>

If I am installing the plugin and mention the plugin statement in the analysis option file Analyzer getting crashed. Getting the below error in developer option of VSCode 

![Screenshot 2021-07-05 at 8 17 29 PM](https://user-images.githubusercontent.com/12973999/124488907-07469600-ddce-11eb-85d8-26fe0b04b60a.png)

**What did you expect to happen?**

**What actually happened?**
Analysis option stopped working. If I restart the VSCode it work once then again same issue 

**Are you willing to submit a pull request to fix this bug?**

**Comment by incendial** [comment]
@Parvinderjit Hi, could you provide formatted version of the config you shared. It's kinda hard to guess. Also, do you have LSP mode on or off?

**Comment by Parvinderjit** [comment]
[analysis_options.yaml.zip](https://github.com/dart-code-checker/dart-code-metrics/files/6771140/analysis_options.yaml.zip)
Hi @incendial This is the analysis_option file. And for the LSP mode I didn't turned it on or off explicitly. I just installed the Flutter plugin in the vs code and using the default configurations. Please let me know if you need any other information

**Comment by incendial** [comment]
@Parvinderjit  Thanks for providing the analysis_options file, it looks totally correct.

You can check lsp mode here:
<img width="927" alt="Screenshot 2021-07-06 at 18 47 52" src="https://user-images.githubusercontent.com/21116742/124630189-da0bed80-de8a-11eb-8755-fc606b7fe1fc.png">

Unfortunately, it's really hard to say, what's wrong. Any chance you can provide a reproducible example?

**Comment by Parvinderjit** [comment]
Yes If try to run the analyzer in LSP mode in that case it is crashing.

**Comment by dkrutskikh** [comment]
@Parvinderjit Hi! I reproduce similar situation only on Flutter stable channel. Could you switch on flutter beta/dev channel and recheck?

**Comment by Parvinderjit** [comment]
@dkrutskikh Hi! I have tried it with flutter beta version (2.3.0-24.1). It is not crashing in LSP mode. But it is not analysing in the IDE itself. You can refer to the screenshot. Problem section in left and terminal output at bottom. 

![Screenshot 2021-07-10 at 6 23 19 PM](https://user-images.githubusercontent.com/12973999/125163833-a1cb1e80-e1ac-11eb-9fed-f20e6e834861.png)

**Comment by incendial** [comment]
@Parvinderjit sorry for the delay. What do you mean by "not analyzing"? Metrics (`source lines of code` is a metric) report is not supported by the plugin integration, it's only supports rules and anti-patterns. And CLI reports all of them.

**Comment by incendial** [comment]
Closing this since there is no response. Feel free to reopen this issue if the problem remains.
