### ISSUE TITLE
[Question] can auto-fixes be available via  ‘dart fix --apply’

### ISSUE THREAD

**Issue by lanbozhang** [dart-code-checker/dart-code-metrics#418]
> Right now auto-fixes are available through an IDE context menu (ex. VS Code Quick Fix).

can we use ` dart fix --apply` to fix all issues that have "has auto-fix"

**Comment by incendial** [comment]
@lanbozhang sorry, but no, `dart fix` doesn't provide any API for plugins to contribute to applied fixes. We have an open feature request to make it possible https://github.com/dart-lang/sdk/issues/46760. Before it's implemented, the only way to use quick fixed is from the IDE context menu as described here: https://dartcodemetrics.dev/docs/analyzer-plugin#applying-quick-fixes.
