### ISSUE TITLE
[Rule change] long-parameter-list must take into account only required and positional parameters

### ISSUE THREAD

**Issue by NaikSoftware** [dart-code-checker/dart-code-metrics#420]
In Flutter can be 5-10 optional parameters. Check out all `.copyWith` methods, constructors. This rule make sense only for positional and required parameters.

**Comment by incendial** [comment]
The idea of this anti-pattern is to keep the amount of parameters small and it won't achieve its goal if only positional and required parameters will be taken into account. So, I think we won't change it that way. But we definitely should take into consideration ignoring `.copyWith`.

**Comment by NaikSoftware** [comment]
@incendial not only copyWith. Check out SDK component constructors. In most cases they have many params, but only 1..3 is required.

**Comment by jangruenwaldt** [comment]
I agree, I think the current lint is barely helpful

**Comment by incendial** [comment]
Fixed in Teams version 1.2.0, it's now a rule https://dcm.dev/docs/teams/rules/common/avoid-long-parameter-list/
