### ISSUE TITLE
[BUG] dependency issue auto_route_generator: ^2.4.0 with dart_code_metrics: ^4.3.1

### ISSUE THREAD

**Issue by PTLam25** [dart-code-checker/dart-code-metrics#466]
* **Dart code metrics version:*4.3.1*
* **Dart sdk version:*2.14.2*

**What did you do? Please include the source code example causing the issue.**
Running pub get command.

**What did you expect to happen?**
No dependency issue **auto_route_generator**: ^2.4.0 and **dart_code_metrics**: ^4.3.1

**What actually happened?**
![image](https://user-images.githubusercontent.com/83693224/134049899-9d91af6b-f7e3-4a6c-a9de-cdfcf8851b69.png)

**Are you willing to submit a pull request to fix this bug?**
No

**Comment by dkrutskikh** [comment]
@PTLam25 fixed in 4.3.2 version
