### ISSUE TITLE
[Question] What do you think about conventional changelog generation?

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#470]
Сurrently we have to manually update `CHANGELOG.md` for each feature. What do you think about automatically generating changelog using [conventional changelog](https://github.com/conventional-changelog/conventional-changelog) tools or GitHub action like [this one](https://github.com/TriPSs/conventional-changelog-action) ?

**Comment by incendial** [comment]
I think we're alright with the current way of updating the changelog. Closing this for now
