### ISSUE TITLE
[Question] Documentation: single source of truth

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#475]
As I see at the moment we have two sources of documentation with duplicate content.

So problems I see here:
* When contributors add new rules or modify existing rules they update rule documentation on this repository and have to publish one additional PR to [website](https://github.com/dart-code-checker/website) repository with the same documentation updates.
* It is actually almost impossible to achieve 100% documentation synchronization between this repository and website repository using the "manual" approach: it's quite easy to forget to make website PR or make website PR with different documentation content.

WDYT about removing duplicate documentation from this repository and point to website documentation from README?

We can use some automatic synchronization workflow too, but this can be much complicated.

**Comment by incendial** [comment]
The docs in this repo are just a part of migration to website. We'll remove them soon. The README file already has no links to it, the issues also point out to website.

**Comment by incendial** [comment]
But yeah, syncronization is a bit of a problem, do you have any suggestions on how we can automate checking for a PR in the website?

**Comment by roman-petrov** [comment]
Unfortunately I do not know any synchronization tools that would be helpful for our case. I didn't knew that docs here are hosted temporarily and will be removed in future so I think we can just close my question if in future we will get all docs hosted in website repo. If I will have some ideas about synchronization - I will open a new issue with a proposal.
