### ISSUE TITLE
[BUG] Memory leak

### ISSUE THREAD

**Issue by fryette** [dart-code-checker/dart-code-metrics#479]
* **Dart code metrics version:** 4.3.3
* **Dart sdk version:** 14.2

We have a mono repo project with around 21 subprojects. After start analyzing memory consumption increased dramatically from 1 to 5GB, after each `flutter pub get` increased again on more than 5GB. We checked that it's doesn't happening if we remove `dart_code_metrics`. 

More details can be founded here
https://github.com/flutter/flutter/issues/90868

**Comment by incendial** [comment]
@fryette could you clarify, calling `flutter pub get` in the same subproject increases the memory consumption or in a different one? Or it doesn't matter?

**Comment by fryette** [comment]
@incendial every subproject where `dart_code_metrics` added increased memory consumption with `flutter pub get` execution.(we have code metrics in every sub project)

**Comment by incendial** [comment]
@fryette thanks for clarification, looks like the problem is investigation by the analyzer team. Hope, we'll figure out the fix.

**Comment by fryette** [comment]
Seems they fixed it, need to check it with the next release.

Close for now.
