### ISSUE TITLE
[Proposal] Merge "website" repository into "dart-code-metrics" repository

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#514]
## Problem

Currently when updating code in `dart-code-metrics` we often also must update documentation which is moved into `website` repository.

From my experience documentation quite often is located in the same repository as code so typical PR contains code & documentations updates. This was true for dart code metrics before `website` repository was introduced.

As I understand, new (current) contributor workflow is:
* Create a PR into `dart_code_metrics` repository only with code updates
* Address review comments, perform requested changes & merge into `dart-code-metrics`
* Create documentation PR into `website` repository
* Address review comments, perform requested changes & merge into `website`

As I see this approach has some drawbacks:
* It's quite easy to forget to create a PR into `website` after code PR is updated
* Problem context can be partially lost for both contributor & reviewers when working on `website` PR after code PR is merged

## Proposal

I propose to merge `website` repository into `dart-code-metrics` repository. Here are some examples of such approach:

### [fvm](https://github.com/leoafarias/fvm) repository ([website](https://fvm.app/))

Website & docs are placed under [website](https://github.com/leoafarias/fvm/tree/main/website) subfolder.

### [melos](https://github.com/invertase/melos) repository ([website](https://melos.invertase.dev/))

As I understood from quickly browsing, docs are placed under [docs](https://github.com/invertase/melos/tree/master/docs) subfolder and website settings are stored in [docs.json](https://github.com/invertase/melos/blob/master/docs.json).

### [flutterfire](https://github.com/FirebaseExtended/flutterfire) repository ([website](https://firebase.flutter.dev/))

Website is placed under [website](https://github.com/FirebaseExtended/flutterfire/tree/master/website) subfolder, docs are placed under [docs](https://github.com/FirebaseExtended/flutterfire/tree/master/docs) subfolder.

**Comment by incendial** [comment]
Thank you for staring this discussion, website is now a part of this repo. The separate repo is archived.

**Comment by roman-petrov** [comment]
@incendial , thank you. Hope the new workflow with website & code in the same repository will not have serious disadvantages.
