### ISSUE TITLE
[Rule change] Rename rules prefixed with `no-` to use `avoid-` prefix

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#520]
We have some rules with `avoid-` and `prefer-` prefixes. But there are also (old?) rules starting with `no-` like 'no-magic-numbers`, 'no-empty-block`. I propose to rename these rules in next major (5.0?) release to `avoid-magic-number`, `avoid-empty-block`, etc.

This will be breaking change and I think we should deprecate old names first and completely stop supporting these old names in a few release cycles.

**Comment by incendial** [comment]
After some time I think we'll keep the rule names as is.
