### ISSUE TITLE
[BUG] exclude still not working

### ISSUE THREAD

**Issue by fredgrott** [dart-code-checker/dart-code-metrics#531]
exclude still not working as I tried the 4.5.0 release and it still flags things in the test folder when I have it set to exclude it.

But, the dep issue is gone, thanks for the update solving that!

**Comment by incendial** [comment]
@fredgrott hi, could you share the config and the platform you use? cc @roman-petrov @dkrutskikh

**Comment by roman-petrov** [comment]
I had problems with rule specific excludes not working on Windows (in both CLI and analyzer plugin). But I don't see this problem after [I fixed this](https://github.com/dart-code-checker/dart-code-metrics/pull/518) in 4.5.0.

So we definitely need more details here:
- `analysis_options.yaml` file
- What operating system do you use?
- Is the problem happening only on both CLI / and IDE?
- What IDE do you use?

The important thing I noticed when exploring dart code metrics code, that exclude folders resolved relative to `analysis_options.yaml` file location. So, for regular repositories to exclude `test` folder you need to use `test/**` pattern, but for monorepos it should be like `'packages/**/test/**'`.

**Comment by incendial** [comment]
@fredgrott sorry for ping, but any chances you can provide more details?
