### ISSUE TITLE
[BUG] avoid-ignoring-return-values triggers on Future<void>

### ISSUE THREAD

**Issue by denis-afanasev** [dart-code-checker/dart-code-metrics#552]
I'm not sure if this should be a question or a bug:

I have an extension method with `Future<void> extensionName(... some args ...)` signature.

After call extension method like `await anObject.extensionName(... some args ...)` I'm getting `Avoid ignoring return values.` message.

The documentation of that rule (https://dartcodemetrics.dev/docs/rules/common/avoid-ignoring-return-values) says nothing about async methods

**Comment by incendial** [comment]
@denis-afanasev hi, looks like a bug to me, we don't check for extension methods.

**Comment by incendial** [comment]
@denis-afanasev could you provide a code sample for this issue? We're not able to reproduce it with our tests, any hint would be useful.
