### ISSUE TITLE
[Question] For GitHub Action, do I need also to edit analysis_options.yaml?

### ISSUE THREAD

**Issue by dvorapa** [dart-code-checker/dart-code-metrics#616]
**What do you want to discuss?**
I couldn't find anything about this topic in the docs. Also is there any default about what to use in analysis_options? I'm used to CodeClimate (from Python) where everything is quite preset, you just need to adjust, when something is too strict/loose.

**Comment by incendial** [comment]
@dvorapa hi, the config from the analysis_options file is shared between plugin, cli and actions setup, so if you need a specific list of rules, metrics, etc. then you need to add config in analysis_options. As for default config, there is no default config yet.

**Comment by dvorapa** [comment]
I see, I should decide which rules then, thanks!!
