### ISSUE TITLE
[Question] Exclude for `anti-pattern`?

### ISSUE THREAD

**Issue by illia-romanenko** [dart-code-checker/dart-code-metrics#636]
**What do you want to discuss?**

Hey, first of all, thanks for working on this awesome plugin!

I wanted to check if there is a similar ability to exclude specific `anti-pattern` for a folder like in here: https://dartcodemetrics.dev/docs/rules/common/prefer-match-file-name#config-example

**Comment by dkrutskikh** [comment]
@illia-romanenko unfortunately no, but we can add `exclude` for anti-patterns in next relese

**Comment by illia-romanenko** [comment]
Thanks, @dkrutskikh. That would be cool! We are looking to disable the `long-method` for tests, which would help.

**Comment by illia-romanenko** [comment]
On the other hand, it looks like the default linter doesn't provide similar `exclude` per rule functionality - so we'll probably stick to the separate analysis_options for tests for now.

**Comment by dkrutskikh** [comment]
Available in 4.10.0 release 🚀
