### ISSUE TITLE
[Command change] - check-unused-files - add `--monorepo` flag

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#683]
It would be nice to have `--monorepo` flag for `check-unused-files` command with the same behaviour as it has in `check-unused-code` command.

Currently, if we have a folder with unused files and `index.dart` that exports all these unused files they are treated as used.
```
project
└───folder_with_unused_files
│   │   index.dart // exports all content from the folder
│   │   unused_file_1.dart
│   │   unused_file_2.dart
│   │   unused_file_3.dart
│   │   ...
│   ...
```

**Comment by dkrutskikh** [comment]
Available in 4.11.0 release 🚀
