### ISSUE TITLE
[Question] How to add severity to a metric

### ISSUE THREAD

**Issue by Prn-Ice** [dart-code-checker/dart-code-metrics#688]
**What do you want to discuss?**
I'd like to force adherence to certain metrics, how can I add severity to a metric?

**Comment by dkrutskikh** [comment]
@Prn-Ice metrics does't generate an issue, metric generate only a value whose contains simple number and violation level (by default level - none). You can define threshold for each metric and if metric calculate the higher number than you defined threshold, that value is assigned violation level warning or higher.

**Comment by Prn-Ice** [comment]
Thanks
