### ISSUE TITLE
[Question] Should or should-not we use the `avoid-non-null-assertion` rule to disallow usage of `!` operator?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-code-checker/dart-code-metrics#703]
I have enabled it tentatively. It is useful because it does point out some cases where potential NPE can happen and I should use defensive programming. However, it is creating so many false alerts (indeed >500). Shall I suppress those false alerts one by one?

By the way, can we configure this rule to suppress things like `WidgetsBinding.instance!`? IMHO people just write like that and it is very normal.

**Comment by incendial** [comment]
@fzyzcjy if you're able to group those false alerts and list it here, we can discuss changing the rule to ignore those cases.

> By the way, can we configure this rule to suppress things like WidgetsBinding.instance!?

No, there are currently no way to suppress specific cases.

**Comment by roman-petrov** [comment]
> By the way, can we configure this rule to suppress things like `WidgetsBinding.instance!`? IMHO people just write like that and it is very normal.

FYI, `WidgetsBinding.instance` is now non-nullable in Flutter master channel https://github.com/flutter/flutter/commit/ab89ce285f76a3fd3a9328ec863f5623cc5ac8bc

**Comment by fzyzcjy** [comment]
> if you're able to group those false alerts and list it here, we can discuss changing the rule to ignore those cases.

Well they are not "false" in the sense that the rule fails. But they are "false" because we really need to use the `!` operator.

Cannot group IMHO. They are often case by case...

> FYI, WidgetsBinding.instance is now non-nullable in Flutter master channel https://github.com/flutter/flutter/commit/ab89ce285f76a3fd3a9328ec863f5623cc5ac8bc

Sounds great!

**Comment by incendial** [comment]
>  But they are "false" because we really need to use the ! operator.

We support different ignoring approaches listed here: https://dartcodemetrics.dev/docs/getting-started/configuration#ignoring-a-rule-or-anti-pattern

**Comment by fzyzcjy** [comment]
> We support different ignoring approaches listed here

Thanks, I know that. But it is quite verbose to write a whole `//ignore` for a single `!`
