### ISSUE TITLE
[BUG] The `dart-code-metrics` *itself* has linter warnings

### ISSUE THREAD

**Issue by fzyzcjy** [dart-code-checker/dart-code-metrics#704]
As is shown below:

![image](https://user-images.githubusercontent.com/5236035/155528884-0e477b65-2bb6-45df-9961-edac91db298a.png)

**Comment by incendial** [comment]
@dkrutskikh could you take a look on that?

**Comment by incendial** [comment]
Looks like we have only 6 issues and they all are about `anti-patterns`. We'll keep then for debugging purpose.
