### ISSUE TITLE
[Rule change] `avoid-non-null-assertion`: For `map[key]!`, not only ignore when `map` is of type `Map`, but also when `map` implements or extends `Map`

### ISSUE THREAD

**Issue by fzyzcjy** [dart-code-checker/dart-code-metrics#721]
For map[key]!, not only ignore when map is of type Map, but also when map implements or extends Map

**What rule do you want to change?**

avoid-non-null-assertion

**Comment by incendial** [comment]
@fryette have you faced this issue with an external code (like some custom Map implementation) or with out own implementation?

**Comment by incendial** [comment]
@fzyzcjy could you share an example for such map? How common is it?

**Comment by fzyzcjy** [comment]
@incendial For example, widely used `ObservableMap`. As long as use mobx.dart, you will use that, and mobx is quite popular choice (even a "flutter favorite" package).

**Comment by incendial** [comment]
Available in 4.14.0 🚀

**Comment by fzyzcjy** [comment]
🎉
