### ISSUE TITLE
[BUG] --set-exit-on-violation-level not work with Bitbucket pipelines CI

### ISSUE THREAD

**Issue by minhnt3** [dart-code-checker/dart-code-metrics#730]
When I run this command: `dart run dart_code_metrics:metrics analyze lib --set-exit-on-violation-level=noted`. There're logs on my console but it does not exit.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/93504649/156728080-c43aebe5-febe-4dd2-8ade-f4ecb7637238.png">

* Dart code metrics version: 4.11.0
* Dart sdk version: 2.16.1

**Comment by incendial** [comment]
@minhnt3 hi, `set-exit-on-violation-level` is for metrics and you listed rules. Try using different flags `fatal-style` and (or)`fatal-warnings`
