### ISSUE TITLE
[BUG] website is down

### ISSUE THREAD

**Issue by DetachHead** [dart-code-checker/dart-code-metrics#747]
https://dartcodemetrics.dev/

![image](https://user-images.githubusercontent.com/57028336/159156144-7b59b8b3-f97f-4bf1-ab08-4f5291758dd8.png)

https://downforeveryoneorjustme.com/dartcodemetrics.dev?proto=https

![image](https://user-images.githubusercontent.com/57028336/159156170-779a09f3-4370-49f3-a8a5-32796821cb3e.png)

**Comment by incendial** [comment]
Looks like the website is down due to DNS provider issues, while it's down you can find all the docs here https://github.com/dart-code-checker/dart-code-metrics/tree/master/website/docs

Sorry for inconvenience, hope the issue will be resolved soon

**Comment by incendial** [comment]
Should be available now

**Comment by DetachHead** [comment]
awesome thanks!
