### ISSUE TITLE
[Question] how do i get the errors to show in intellij?

### ISSUE THREAD

**Issue by DetachHead** [dart-code-checker/dart-code-metrics#749]
**What do you want to discuss?**

[the readme](https://github.com/dart-code-checker/dart-code-metrics#analyzer-plugin) seems to suggest that the issues get highlighted in vscode, but that doesn't seem to be the case in intellij

![image](https://user-images.githubusercontent.com/57028336/159164328-2bff7d44-633a-410b-80a9-15128cf1ce21.png)

```
>flutter pub run dart_code_metrics:metrics analyze lib
lib\main.dart:
WARNING Parameter is unused.
        lib\main.dart:117:10
        avoid-unused-parameters : https://dartcodemetrics.dev/docs/rules/common/avoid-unused-parameters

STYLE   Block is empty. Empty blocks are often indicators of missing code.
        lib\main.dart:117:24
        no-empty-block : https://dartcodemetrics.dev/docs/rules/common/no-empty-block
```

related: https://youtrack.jetbrains.com/issue/WEB-55130

**Comment by incendial** [comment]
Please check out the plugin setup https://dartcodemetrics.dev/docs/analyzer-plugin

**Comment by DetachHead** [comment]
that doesn't seem to work anymore since i updated flutter to the master channel, no longer seeing errors in intellij despite having the plugin enabled in `analysis_options.yaml`:
```yaml
analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  rules:
    - no-empty-block
```

```
>flutter --version
Flutter 2.13.0-0.0.pre.242 • channel master • https://github.com/flutter/flutter.git
Framework • revision 10142b5817 (11 hours ago) • 2022-03-24 18:47:19 -0700
Engine • revision 816c8651d8
Tools • Dart 2.17.0 (build 2.17.0-232.0.dev) • DevTools 2.11.4
```

**Comment by incendial** [comment]
@DetachHead sorry for the long response, this looks like a in the integration, could you open an issue in dart sdk repo?

**Comment by DetachHead** [comment]
@incendial https://github.com/dart-lang/sdk/issues/48682

**Comment by DetachHead** [comment]
this is fixed now
