### ISSUE TITLE
[Question] check-unused-files how to exclude **/.dart_tool/** and **/build/**

### ISSUE THREAD

**Issue by lukepighetti** [dart-code-checker/dart-code-metrics#777]
Hello, I am trying to pipe the result of `melos list --parseable` into `dart_code_metrics:metrics check-unused-files`, and I'm having trouble getting DCM to ignore common folders such as `.dart_tool` and `build`.

```
├── .dart_tool <-- ignore
├── build <-- ignore
├── lib
├── packages
│   ├── bar
│   │   ├── .dart_tool <-- ignore
│   │   ├── build <-- ignore
│   │   ├── lib
│   ├── baz
│   │   ├── .dart_tool <-- ignore
│   │   ├── lib
│   ├── biff
│   │   ├── .dart_tool <-- ignore
│   │   ├── lib
│   │   └── src
│   └── foo
│       ├── .dart_tool <-- ignore
│       ├── bin
│       ├── lib
│       └── test
└── test
```

if I run `flutter pub run dart_code_metrics:metrics check-unused-files --exclude='**/.dart_tool/**' /absolute/path/to/packages/bar` then everything in `packages/bar/.dart_tool` is ignored 👍

But if I run `flutter pub run dart_code_metrics:metrics check-unused-files --exclude='**/.dart_tool/**','**/build/**' /absolute/path/to/packages/bar` or any permutation of the following

- `'**/.dart_tool/**','**/build/**'`
- `'**/.dart_tool/**,**/build/**'`
- `'**/.dart_tool/**, **/build/**'`
- `**/.dart_tool/**, **/build/**`

It will not ignore `packages/bar/.dart_tool` OR `packages/bar/build` 🥲

So, any thoughts on if there's a way to pass a list of package directories to `check-unused-files` and have it work in a predictable manner?

**Comment by incendial** [comment]
Hi, I'm not sure that there should be multiple quotes, have you tried `'**/.dart_tool/**,**/build/**'` instead?

**Comment by incendial** [comment]
Hi, initially I though that `'**/.dart_tool/**, **/build/**'` should work, but now I'm confused too. Investigating...

**Comment by incendial** [comment]
Found out, that there is a bug with the path being separated to several ones by comma (it wasn't at all 😄). Fix is on the way

**Comment by incendial** [comment]
@lukepighetti sorry for the delay, but could you try this https://pub.dev/packages/glob#match-one-of-several-possibilities syntax? Looks like it should work

**Comment by incendial** [comment]
@lukepighetti any chance you can take a look? (Sorry for pinging, but if you say it doesn't work for you, I'll start working on a fix)
