### ISSUE TITLE
flutter_test analyzer issue

### ISSUE THREAD

**Issue by marinkobabic** [dart-code-checker/dart-code-metrics#788]
`Because every version of flutter_test from sdk depends on test_api 0.4.8 and test >=1.20.0 depends on test_api 0.4.9, flutter_test from sdk is incompatible with test >=1.20.0.
And because no versions of test match >1.19.5 <1.20.0 and test 1.19.5 depends on analyzer >=1.0.0 <3.0.0, if flutter_test from sdk and test >=1.19.5 then analyzer >=1.0.0 <3.0.0.
And because octa_appsettings depends on dart_code_metrics ^4.13.0 which depends on analyzer >=3.0.0 <3.4.0, flutter_test from sdk is incompatible with test >=1.19.5.
So, because octa_appsettings depends on both flutter_test from sdk and test ^1.19.5, version solving failed.
`
possible to user a different version of analyzer?

**Comment by dkrutskikh** [comment]
@marinkobabic please try new version
