### ISSUE TITLE
"Basic configuration" on dart.dev omits important config setup

### ISSUE THREAD

**Issue by giorgio79** [dart-code-checker/dart-code-metrics#794]
The main page at https://pub.dev/packages/dart_code_metrics omits the config mentioned
https://dartcodemetrics.dev/docs/analyzer-plugin

The plugin needs to be setup so:
```
analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics: ... # package configuration
```

**Comment by dkrutskikh** [comment]
@giorgio79 thank you for feedback, can you make PR with mentioned improvements?

**Comment by incendial** [comment]
@giorgio79 since the package can be used as a plugin or / and cli, plugin setup is not considered basic. I'm not sure that it should be added.

**Comment by incendial** [comment]
Closing this, feel free to reopen if you disagree.
