### ISSUE TITLE
[New Feature] Ability to export the result in table form into .txt or .docx file

### ISSUE THREAD

**Issue by AbhishekDoshi26** [dart-code-checker/dart-code-metrics#817]
**Please describe what the rule should do:**
The current analyzer rules work like a charm. But these rules would be used by someone who is reviewing the project or the entire app, which means he/she will have to provide the report. It would be a good option to have the ability to export the result of all analyzer command in a table form into a .txt or .docx or even a .pdf file.

**What category of rule is this? (place an "X" next to just one item)**

[ ] Warns about a potential error (problem)
[x] Suggests an alternate way of doing something (suggestion)
[ ] Other (please specify:)

**Comment by dkrutskikh** [comment]
@AbhishekDoshi26 thank you for feedback. Can you provide example of what you need?

**Comment by incendial** [comment]
@AbhishekDoshi26 a kind ping, an example would be a nice thing to have 🙂
