### ISSUE TITLE
[Question] Add support to automatically ignore rule

### ISSUE THREAD

**Issue by itsJoKr** [dart-code-checker/dart-code-metrics#838]
It would be great if dart-code-metrics issues could be ignored like with analyzer issues. 

For every analyzer issue I can do:
_Option+Enter -> Ignore for line_ or _Ignore for file_

Without it, I need to go to docs to find out name of the rule and then write it manually. Right now it's a bit of a hassle to adopt this on big projects, since I have hundreds of issues and ignore could help a lot in adoption.

**Comment by incendial** [comment]
@itsJoKr hi, thank you for suggesting this and sorry for inconvenience. There is actually another issue about the same problem https://github.com/dart-code-checker/dart-code-metrics/issues/806, so I'm closing this as a duplicate.

> Without it, I need to go to docs to find out name of the rule and then write it manually.

What IDE do you use? Coz you can find the id of the rule, that triggered the highlight in the VS Code, if you hover the highlighted part.
