### ISSUE TITLE
[Feature]  Make use of GitHubs new action summaries

### ISSUE THREAD

**Issue by ueman** [dart-code-checker/dart-code-metrics#840]
GitHub introduced Action summaries (see [this blog post](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)). It would be really cool if you could make use of it.

**Comment by dkrutskikh** [comment]
@ueman thanks for feature request!  Please move this issue to the action report.

**Comment by ueman** [comment]
Oh sorry, will do.
