### ISSUE TITLE
[BUG] Comatibility with Dart 2.17 & analyzer 4.0

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#843]
I have a problem using `build_runner` + `dart_code_metrics` on my codebase which uses new [super parameters](https://github.com/dart-lang/language/issues/1855) feature introduced in Dart 2.17.

The problem is that `dart_code_metrics` currently has a restriction for ` analyzer: ">=2.4.0 <3.4.0"` so the `analyzer` package can not be resolved to `4.0.0` and `build_runner` fails when sees super parameters in code. Can we upgrade analyzer upper bound to `4.0.0`?

**Comment by incendial** [comment]
Should be fixed in 4.15.1
