### ISSUE TITLE
[Feature request] Introduce autosorting for member-ordering-extended rule

### ISSUE THREAD

**Issue by fryette** [dart-code-checker/dart-code-metrics#847]
The main issue with that rule is that it's impossible to apply it to the whole codebase.

I would like to ask you to provide a way for applying it automatically to the whole codebase.
It can be via console or any suitable way that the project can use across the team

**Comment by incendial** [comment]
We thought about introducing auto-fixing through `dart fix` API, but unfortunately there is still no way to extend it. I have another idea, how to achieve this for DCM, will try to create some prototype soon

**Comment by fryette** [comment]
Interesting case I found how to moor did migration to drift.

Probably you can introduce such commands as well 
link: https://1j2.com/help/how-to-find-udid-of-iphone-or-ipad-without-mac-or-pc/

**Comment by incendial** [comment]
> Interesting case I found how to moor did migration to drift.
> 
> Probably you can introduce such commands as well link: https://1j2.com/help/how-to-find-udid-of-iphone-or-ipad-without-mac-or-pc/

Sorry, I didn't get the idea. Could you elaborate?

**Comment by incendial** [comment]
Yeah, looks like it thanks! I'll close this one as duplicate. This feature is work in progress right now, but no commitments yet.
