### ISSUE TITLE
[Question] Rules violations are not highlighted in report generated by dart metrics analysis

### ISSUE THREAD

**Issue by sherrychhabra51** [dart-code-checker/dart-code-metrics#907]
Hi Guys, 

I was trying to implement dart code metrics analysis in one of my project. I added this plugin in my project along with flutter analyzer rules. 

`dart_code_metrics: ^4.16.0`

When I ran code analysis on my project using below command, it clearly states all the issues at the top of each file like cyclomatic complexity, Source lines of code, maximum nesting, issues etc.

`flutter pub run dart_code_metrics:metrics analyze lib --reporter=html --fatal-style`

When we start analysis on each file by going line by line, we can clearly see metrics analysis like number of parameters of each method , its cyclomatic complexity etc . But I am not able to understand two things:-

1. What does this Issues and Design Issues at the top right suggest (Please refer screenshot attached).

2. All of the generated report files in project have no information on what rule the app is violating. I have attached a reference file as well generated by the dart metrics analyzer. Can you tell me why report does not explain rules violation like whether there is any line violating the **newline-before-return** rule,  **prefer-conditional-expressions** rules is getting violated , which line is violation the rule etc. because if I run flutter analyzer then it clearly states the rules that is violated based on the rules defined in analysis_options.yaml file.

**Link for HTML generated**
https://drive.google.com/file/d/14XiTHOBMcnQ9qkRdCNYaESkYIzqGMm6m/view?usp=sharing

**Screenshot for one of the files from generated report in which you can see 5 issues and 3 Design issues at the top but does not explain what are those issues and design issues.**

<img width="1787" alt="Screenshot 2022-07-04 at 1 02 30 PM" src="https://user-images.githubusercontent.com/12271877/177104743-7d1a5907-ca64-40ab-8bda-51f93bada24d.png">

**Here is the sample analysis_options.yaml file that I am using for testing **

`analyzer:
  plugins:
    - dart_code_metrics
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    unnecessary_null_comparison: ignore
  exclude:
    - "bin/cache/**"
    - "dev/conductor/lib/proto/*"

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_require_non_null_named_parameters
    - always_specify_types
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - control_flow_in_finally
    - depend_on_referenced_packages
    - deprecated_consistency
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - iterable_contains_unrelated_type
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - list_remove_unrelated_type
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_default_cases
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_logic_in_create_state
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    - only_throw_errors 
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - secure_pubspec_urls
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_init_formals
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_super_parameters
    - use_test_throws_matchers
    - valid_regexps
    - void_checks

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return:
        severity: style
    - no-boolean-literal-compare:
        severity: style
    - no-empty-block:
        severity: style
    - prefer-conditional-expressions:
        severity: style
    - no-equal-then-else
    - binary-expression-operand-order
    - avoid-global-state:
        severity: style
    - avoid-ignoring-return-values
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        max-identifier-length: 30
    - prefer-immediate-return
    - prefer-moving-to-variable
    - prefer-trailing-comma
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
  anti-patterns:
    - long-method
    - long-parameter-list`

**Comment by incendial** [comment]
@dkrutskikh can you take a look please?

**Comment by sherrychhabra51** [comment]
@dkrutskikh Did you get a time to look into it.

**Comment by incendial** [comment]
Showing rule violations in HTML report is not planned to be implemented anytime soon.
