### ISSUE TITLE
[Question] check-unused-code: Ignore 'unused class' warning for some classes

### ISSUE THREAD

**Issue by quentinleguennec** [dart-code-checker/dart-code-metrics#908]
Is there a way to mark a given class to be excluded from the list of results returned by `check-unused-code`? For example by adding something like `// ignore: unused_element` just above the class?

Thanks

**Comment by incendial** [comment]
@quentinleguennec hi, no, there is currently no way to exclude any specific class from the report, only a whole file via analyzer excludes section in analysis_options file. Can you share, why do you need that?

**Comment by quentinleguennec** [comment]
Hi @incendial , I have some classes, getter, and top level constants and functions that I don't currently use but still want to keep around. 

For example I have a few top level functions to convert imperial system units to metric system, like `convertFeetToMeters(...)`

And I also have `convertMetersToFeet(...)` which I currently don't use but want to keep it as part of a set. I'd like to hide it from the list of returned unused.

**Comment by incendial** [comment]
Available in 4.17.0 🚀
