### ISSUE TITLE
[Rule change] Let `ban-name` ban things like `DateTime.now`

### ISSUE THREAD

**Issue by fzyzcjy** [dart-code-checker/dart-code-metrics#927]
To allow testability, it would be great to ban all `DateTime.now` and use `clock.now` instead. Thus, we can extend `ban-name` to do so.

**What rule do you want to change?**

**How will the change be implemented? (New option, new default behavior, etc.)?**

**Please provide some example code that this change will affect:**

```dart
```

**What does the rule currently do for this code?**

**What will the rule do after it's changed?**

**Are you willing to submit a pull request to implement this change?**

**Comment by incendial** [comment]
Available in 5.1.0 🚀

**Comment by fzyzcjy** [comment]
🎉
