### ISSUE TITLE
[Question] How to import all rules and disable the ones not relevant to a project?

### ISSUE THREAD

**Issue by NickBalnaves** [dart-code-checker/dart-code-metrics#939]
**What do you want to discuss?**
Inspired by https://pub.dev/packages/all_lint_rules_community is there a way to include all rules in this package and then disable or alter rules that aren't relevant to a project?

**Comment by incendial** [comment]
@NickBalnaves no, it's not possible, but will be when #459 is implemented. Closing this for now.
