### ISSUE TITLE
[New rule] close-method param for member-ordering-extended rule

### ISSUE THREAD

**Issue by justjew** [dart-code-checker/dart-code-metrics#956]
I always put dispose/close/cancel methods to the bottom of class. I am clearly sure it is a good practice.
Unfortunately `member-ordering-extended` has only `dispose-method` option.
Also I did not find how I can create custom ordering rule.

**What category of rule is this? (place an "X" next to just one item)**

- [ ] Warns about a potential error (problem)
- [ ] Suggests an alternate way of doing something (suggestion)
- [ ] Other (please specify:)

**Comment by justjew** [comment]
Oh, also I found out that `dispose-method` works only inside Widgets

**Comment by incendial** [comment]
@justjew hi, yeah, we only supported named methods for the widgets at this point and I'm not sure how make this configuration flexible. We can add support for *-method, and check if * equals to any method of a class, but I'm not sure that there will be no cases, when the user would want to have one order for "services" and another for "widgets".

**Comment by justjew** [comment]
@incendial what about `w-*-method`, `s-*-method`, where prefix W means Widget and S means Service? And * is method name

**Comment by justjew** [comment]
It would be flexible enough

**Comment by incendial** [comment]
Unfortunately, services and widgets are also limited to projects that use such terms. One options would be to introduce patterns for the entries, like close-method for *Service classes, but it will make the config more complicated

**Comment by justjew** [comment]
By services I meant anything but widgets. Not *Service classes.

**Comment by incendial** [comment]
Ah, I got it. Maybe you're right and that would be enough.

**Comment by justjew** [comment]
Anyway, there should be some customization

**Comment by incendial** [comment]
Available in 5.0.0 🚀 , check out the docs for `widget-order` and `order` setup
