### ISSUE TITLE
[Question] How do CI with a Monorepo?

### ISSUE THREAD

**Issue by ItaloF532** [dart-code-checker/dart-code-metrics#970]
Hi, I work with a monorepo and a trying to implement the dart code metrics CI, but I don't found any example of it.
I achieved with melos in CI, but without dart code metrics CI, I can't have comments for te code issues in PR. 

Can you guys give me an example of how can I use the dart code metrics with a mono repo in CI? Please

**Comment by incendial** [comment]
@ItaloF532 hi, sorry for the delay, you do have melos, right?

**Comment by incendial** [comment]
So, if you use melos, please check out how GetStream uses Dart Code Metrics with Melos https://github.com/GetStream/stream-chat-flutter/blob/develop/.github/workflows/dart_code_metrics.yaml
